# Generated by Django 4.1.6 on 2023-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=350)),
                ('subtitle_text', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date posted')),
                ('body_text_link', models.CharField(max_length=500)),
                ('project_id', models.IntegerField(null=True)),
                ('tag_1', models.IntegerField(null=True)),
                ('tag_2', models.IntegerField(null=True)),
                ('tag_3', models.IntegerField(null=True)),
            ],
        ),
    ]
