# Generated by Django 4.1.6 on 2023-02-13 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('blog', '0002_alter_blogpost_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body_text_link',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_tag_1', to='projects.tag'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_tag_2', to='projects.tag'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tag_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_tag_3', to='projects.tag'),
        ),
    ]
