name: Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to Server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}
      run: |
        export SSHPASS=$SSH_PASSWORD
        sshpass -e ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST "mkdir -p $TARGET_DIRECTORY"
        sshpass -e rsync -avz -e "ssh -o StrictHostKeyChecking=no -p $PORT" --exclude='.git/' --exclude='.github/' ./ $USERNAME@$HOST:$TARGET_DIRECTORY
        sshpass -e ssh -o StrictHostKeyChecking=no -p $PORT $USERNAME@$HOST "cd $TARGET_DIRECTORY && ./restart_script.sh"
